name: Deploy to Google Cloud Run

on:
  push:
    branches:
      - master
  workflow_dispatch:

env:
  PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  SERVICE_NAME: bantu-website
  IMAGE: gcr.io/${{ secrets.GCP_PROJECT_ID }}/bantu-website

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v0.2.1
        with:
          project_id: ${{ env.PROJECT_ID }}
          service_account_key: ${{ secrets.CLOUDRUNNER }}
          export_default_credentials: true

      - name: Build and push Docker image
        run: |
          docker build -t ${{ env.IMAGE }} .
          docker push ${{ env.IMAGE }}

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy ${{ env.SERVICE_NAME }} \
            --image ${{ env.IMAGE }} \
            --region us-central1 \
            --platform managed \
            --allow-unauthenticated
            --update-secrets=/mnt/config=banconfig:latest, ENV=config
            --update-secrets=/mnt/credentials.json=firebase_sa:latest, ENV=credentials
            --update-secrets=mnt/creds.json=cloudrunner:latest, ENV=creds
